---
openapi: 3.0.3
security:
  - testAuth : []
info:
  title: Accounts
  description: Interact with accounts
  version: 1.0.0
  termsOfService: https://example.com/tos
  license:
    name: Apache 2.0
    url: https://opensource.org/licenses/Apache-2.0
  contact:
    name: Matt Ball
    email: matt@postman.com
    url: se.postman.com
servers:
  - url: https://553368b7-c39b-44a7-9bdc-b3df7563dfc6.mock.pstmn.io
paths:
  /accounts/create:
    post:
      summary: Create
      description: Create
      operationId: create
      requestBody:
        content:
          application/json:
            "schema":
              "$ref": "#/components/schemas/Account"
            example:
              holder: "{{$randomUUID}}"
              type: "{{$randomBankAccountName}}"
      responses:
        "200":
          description: ""
        "500":
          description: ""
  /accounts/{accountNumber}/overview:
    get:
      summary: Overview
      description: Overview
      operationId: overview
      parameters:
        - $ref: "#/components/parameters/accountNumber"
      responses:
        "200":
          description: ""
        "500":
          description: ""
  "/accounts/{accountNumber}/statement/date":
    get:
      tags:
        - Statement
      summary: Date
      description: Date
      operationId: date
      requestBody:
        content:
          application/form-urlencoded:
            schema:
              $ref: "#/components/schemas/DateRange"
            example:
              from: "{{$randomDatePast}}"
              to: "{{$randomDateRecent}}"
      responses:
        "200":
          description: 200 OK
          content:
            application/json:
              examples:
                200 OK:
                  value: "{\n    \"period\": {\n        \"from\": \"{{$randomDatePast}}\",\n        \"to\": \"{{$randomDateRecent}}\"\n    },\n    \"balance\": {\n        \"opening\": {{$randomPrice}},\n        \"closing\": {{$randomPrice}}\n    },\n    \"money\": {\n        \"in\": {{$randomPrice}},\n        \"out\": {{$randomPrice}}\n    },\n    \"transactions\": [\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        },\n        {\n            \"date\": \"{{$randomDateRecent}}\",\n            \"description\": \"{{$randomCompanyName}}\",\n            \"type\": \"{{$randomTransactionType}}\",\n            \"amount\": {{$randomPrice}},\n            \"balance\": {{$randomPrice}}\n        }\n    ]\n}"
        "500":
          description: ""
    parameters:
      - $ref: "#/components/parameters/accountNumber"
  "/accounts/{accountNumber}/statement/latest":
    get:
      tags:
        - Statement
      summary: Latest
      description: Latest
      operationId: latest
      responses:
        "200":
          description: ""
        "500":
          description: ""
    parameters:
      - $ref: "#/components/parameters/accountNumber"
components:
  schemas:
    Account:
      type: object
      description: Details for an account
      properties:
        holder:
          type: string
          description: ID of customer
          example: "{{$randomUUID}}"
        type:
          type: string
          description: Name of account
          example: "{{$randomBankAccountName}}"
    DateRange:
      type: object
      description: Provide a date range
      properties:
        from:
          type: string
          description: Date from
          example: "{{$randomDatePast}}"
        to:
          type: string
          description: Date to
          example: "{{$randomDateRecent}}"
  parameters:
    accountNumber:
      name: accountNumber
      description: Number for the account being accessed
      in: path
      example: 12345678
      required: true
      schema:
        type: string
  securitySchemes:
    testAuth:
      type: http
      scheme: basic
tags:
  - name: Statement